title: Alex Romanowski
logo: "/images/headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://www.linkedin.com/in/alex-romanowski/">LinkedIn</a> 
  <br>
  <a href="/pdf/Alex_Romanowski_Resume_2_21_23.pdf" class="btn btn--info">Resume</a>  
  <br>
  # <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  # <br>
  <a href="https://github.com/ajr423">GitHub</a>  


  
theme: jekyll-theme-minimal
